log_level: debug
cores: [ 1, 2 ]
memory:
    packet_pool: 8192
    shared_memory: 1024
nics:
  - dev: enp3s0
    ipv6: fe80::2
    rx_queue: 128
    tx_queue: 128
    promisc: 1
  - dev: enp4s0
    ipv6: fe80::2
    rx_queue: 128
    tx_queue: 128
    promisc: 1

loadbalancer:
    queue_size: 2048
    _tas:
      - time: 300000
        prios: [ 3 ]
      - time: 300000
        prios: [ 2, 3 ]
      - time: 400000
        prios: [ -1 ]
    cbs:
        3:
            high: 1080
            low: -3504
            idle:  700000000
            send: -300000000
