log_level: debug
cores: [ 0 ]
memory:
    packet_pool: 1024
    shared_memory: 1024
nics:
  - dev: enp37s0
    ipv6: fe80::2
    rx_queue: 2
    tx_queue: 1
    promisc: 1

loadbalancer:
    tas:
      - time: 300000
        prios: [ 3 ]
      - time: 300000
        prios: [ 2, 3 ]
      - time: 400000
        prios: [ -1 ]
