log_level: debug
cores: [ 0, 1 ]
memory:
    packet_pool: 8192
    shared_memory: 1024
nics:
  - dev: enp3s0
    ipv6: fe80::2
    rx_queue: 1024
    tx_queue: 1024
    promisc: 1
  - dev: enp4s0
    ipv6: fe80::2
    rx_queue: 1024
    tx_queue: 1024
    promisc: 1

loadbalancer:
    queue_size: 2048
    _tas:
      - time: 300000
        prios: [ 3 ]
      - time: 300000
        prios: [ 2, 3 ]
      - time: 400000
        prios: [ -1 ]
    cbs:
        3:
            high: 463
            low: -8220
            idle:  300000000
            send: -700000000
