name: Build

on:
  - push
  - pull_request

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Install clang-format
        run: sudo apt install -qqy --no-install-recommends clang-format-12
      - name: Run clang-format
        run: bin/check-clang-format
      - name: shellcheck
        uses: ludeeus/action-shellcheck@master

  build:
    runs-on: ubuntu-latest
    steps:
      - name: install build tools
        run: sudo apt install -qqy --no-install-recommends gcc cmake ninja-build meson
      - name: Checkout
        uses: actions/checkout@master
        with:
            submodules: recursive
      - name: Install dpdk
        run: |
            curl -o dpdk.tar.xz -L https://fast.dpdk.org/rel/dpdk-20.11.2.tar.xz
            tar -xf dpdk.tar.xz
            pushd dpdk-stable-20.11.2
            meson build
            ninja -C build install
            popd
      - name: build
        run: |
            cmake -B build -G Ninja -DBUILD_EXAMPLES=ON .
            cmake --build build
