name: Build

on:
  - push
  - pull_request

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Install clang-format
        run: sudo apt install -qqy --no-install-recommends clang-format-12
      - name: Run clang-format
        run: bin/check-clang-format
      - name: shellcheck
        uses: ludeeus/action-shellcheck@master

  build:
    runs-on: ubuntu-latest
    steps:
      - name: install build tools
        run: sudo apt install -qqy --no-install-recommends gcc cmake ninja-build
      - name: Checkout
        uses: actions/checkout@master
        with:
            submodules: recursive
      - name: build
        run: |
            cmake -B build -G Ninja -DBUILD_EXAMPLES=ON .
            cmake --build build
